### PR TITLE
Correctly filter messages coming from Hubot itself + Add join events

### PR DESCRIPTION
**Pull request by antoinealb**
This PR adds support for on join events. It is currently based on my previous PR (#10) but I can rebase it on master if it is required.

### CODE REVIEW

**Comment by hhaidar** [comment]
@antoinealb awesome, I'll try this out later today and get it merged!

**Comment by antoinealb** [comment]
After a bit of testing on my side, I should add some filtering: currently it monitor enter events on all rooms, not only the one it joined :-1:

**Comment by hhaidar** [comment]
@antoinealb ah that's right. It's because we use join/leave to track users in the room list view.

**Comment by antoinealb** [comment]
Any idea on what would be the best strategy for avoiding this ? I was thinking about checking if `user.room` is in  `LCB_ROOMS`, but I am not very familiar with the codebase.

**Comment by hhaidar** [comment]
@antoinealb yea that's what I was thinking for now.

We can do a better job with this in the main repo, like namespacing these events under a different socket.io room.

**Comment by antoinealb** [comment]
Okay, I fixed it.

**Comment by hhaidar** [comment]
Thanks :)

**Pull request merged**
